server:
  port: 9527

spring:
  application:
    name: cloud-getway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能,利用微服务进行路由
      routes:
         # 路由的ID, 没有固定规则但要求唯一,建议配合服务器名
        - id: payment_routh1
          # 匹配后提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service  # 匹配后提供服务的路由地址
          predicates:
             # 断言,路径相匹配的进行路由
            - Path=/payment/get/**
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service  # 匹配后提供服务的路由地址
          predicates: # 断言
            - Path=/payment/lb/**
#            - After=2020-03-09T14:01:55.277+08:00[Asia/Shanghai]  # 时间要在这个时间只后才能访问
#            - Cookie=username,wenting
#            - Header=X-Request-Id, \d+    # 请求头要有X-Request-Id属性,并且值为整数的正则表达式
#            - Host=**.atguigu.com    # 主机名必须是 符合匹配
#            - Method=GET  # 必须是get请求
#            - Query=username, \d+    # 要有参数名username并且值还要是整数才能路由
eureka:
  instance:
    hostname: cloud-getway-service
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    fetch-registry: true
    register-with-eureka: true
